spring.ai.openai.api-key=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
spring.application.name=SpringAI
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.embedding.provider=ollama
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.main.allow-bean-definition-overriding=true
